[project]
name = "vela-example-generator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ethos-u-vela>=4.5.0",
    "numpy>=2.3.5",
    "tensorflow>=2.20.0",
]
